<#--<#assign-->
<#--    known = currentUserName!-->
<#-->-->

<#--<#if known??>-->
<#--    <#assign-->
<#--    email = currentEmail!-->
<#--    name = "unknown user"-->
<#--    role = "USER"-->
<#--    >-->
<#--&lt;#&ndash;.seq_contains('ADMIN')&ndash;&gt;-->
<#--<#else>-->
<#--    <#assign-->
<#--    email = "unknown email"-->
<#--    name = "unknown user"-->
<#--    role = "USER"-->
<#--    >-->
<#--</#if>-->